[build]
  command = "npm run build"
  publish = "out"

# Optionally, specify functions directory if using Netlify Functions
# [functions]
#   directory = "netlify/functions"

# Disable the Netlify Next.js plugin
# [[plugins]]
#   package = "@netlify/plugin-nextjs"
#   disabled = true 

[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200 

[build.environment]
  NETLIFY_NEXT_PLUGIN_DISABLED = "1" 