[build]
  command = "npm run build"
  publish = "out"

# Optionally, specify functions directory if using Netlify Functions
# [functions]
#   directory = "netlify/functions"

# Disable the Netlify Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Disable the custom images redirect
[[redirects]]
  from   = "/images/*"
  to     = "/images/:splat"
  status = 200
  force  = true 